# vim: set ft=yaml ts=2 expandtab:
---

- name: converge containers
  hosts: localhost
  connection: local

  tasks:

  - name: a rocky 8 container is present
    mafalb.containers.buildah_container:
      name: rocky_container
      image: quay.io/rockylinux/rockylinux:8
      state: present

  - name: a preexisting rocky 8 container is absent
    mafalb.containers.buildah_container:
      name: preexisting_rocky_container
      state: absent

...
