# vim: set ft=yaml ts=2 expandtab:
---

- name: verify
  hosts: localhost
  connection: local

  tasks:

  - block:

    - name: the rocky 8 container is absent
      mafalb.containers.buildah_container:
        name: rocky_container
        state: absent
      register: _rocky_container

    - name: the rocky 8 container is absent
      mafalb.containers.buildah_container:
        name: rocky_container
        state: absent
      register: _rocky_container

    - name: assert that rocky_container was present
      assert:
        that:
        - not _rocky_container.changed|bool

  - block:

    - name: a preexisting rocky 8 container is absent
      mafalb.containers.buildah_container:
        name: preexisting_rocky_container
        state: absent
      register: _preexisting_rocky_container

    - name: assert that rocky_container was present
      assert:
        that:
        - not _preexisting_rocky_container.changed|bool

...
