# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:  # yamllint disable-line rule:truthy

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 6'

jobs:

  SANITY:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

      matrix:

        include:

        - ansible_version: '2.9'
          ansible_pip_version: '<2.10'
          python-version: 2.7
          ansible-lint_version: '==4.*'

        - ansible_version: '2.9'
          ansible_pip_version: '<2.10'
          python-version: 3.5
          ansible-lint_version: '<5'
          cryptography_version: '<3.1'

        - ansible_version: '2.9'
          ansible_pip_version: '<2.10'
          python-version: 3.6

        - ansible_version: '2.9'
          ansible_pip_version: '<2.10'
          python-version: 3.7

        - ansible_version: '2.9'
          ansible_pip_version: '<2.10'
          python-version: 3.8


        - ansible_version: '2.10'
          ansible_pip_version: '<4'
          python-version: 3.6

        - ansible_version: '2.10'
          ansible_pip_version: '<4'
          python-version: 3.7

        - ansible_version: '2.10'
          ansible_pip_version: '<4'
          python-version: 3.8

        - ansible_version: '2.10'
          ansible_pip_version: '<4'
          python-version: 3.9


        - ansible_version: '2.11'
          ansible_pip_version: '<5'
          python-version: 3.6

        - ansible_version: '2.11'
          ansible_pip_version: '<5'
          python-version: 3.7

        - ansible_version: '2.11'
          ansible_pip_version: '<5'
          python-version: 3.8

        - ansible_version: '2.11'
          ansible_pip_version: '<5'
          python-version: 3.9

    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      ANSIBLE_PYTHON_INTERPRETER: ${{ matrix.python-version }}/bin/python

    defaults:
      run:
        working-directory: ansible_collections/mafalb/container

    steps:

    - name: checkout collection mafalb.container
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/container

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: python version
      run: |
        python --version
        which python
        whereis python
        python3 --version
        which python3
        whereis python3
        ls -l /opt/hostedtoolcache/Python/

    - name: install shellcheck
      run: sudo apt install shellcheck

    - name: install ansible
      run: |
        pip install virtualenv
        virtualenv ~/virtualenv
        . ~/virtualenv/bin/activate
        pip install wheel
        pip install -U pip setuptools
        pip install 'ansible${{ matrix.ansible_pip_version }}' 'ansible-lint${{ matrix.ansible-lint_version }}' 'cryptography${{ matrix.cryptography_version }}' 'flake8<3.9'  pylint  'pycodestyle<2.7'

    - name: check ansible version
      run: |
        source ~/virtualenv/bin/activate
        ansible --version
        which ansible-test
        ansible-lint --version
        ansible --version | grep "^ansible.* ${{ matrix.ansible_version }}"

    - name: check python version
      run: |
        source ~/virtualenv/bin/activate
        ansible --version | grep "^\s*python.* ${{ matrix.python-version }}"

    - name: lint
      run: |
        source ~/virtualenv/bin/activate
        if ansible-lint --version|grep "^ansible-lint 4"
        then
            ANSIBLE_LINT_VERSION=4
        fi
        . tests/lint.sh requirements ${{ matrix.python-version }}


  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        ansible_version:
        - '2.9'
        - '2.10'
        - '2.11'

    env:

      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_IMAGE: ${{ matrix.image }}
      CI_HOSTNAME: ci-${{ matrix.target }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/container

    steps:

    - name: checkout collection mafalb.container
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/container

    - name: run integration tests
      run: ansible-test integration --color

    - name: install molecule
      run: |
        ansible-galaxy collection install mafalb.ansible
        ansible-playbook -e ansible_python_interpreter=python3 -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }} -t all,debug

    # use our ansible
    #
    - name: check ansible version
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        ansible --version | grep "^ansible.* ${{ matrix.ansible_version }}"

    - name: molecule tests
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test

...
